# Generated by Django 4.2.9 on 2024-01-27 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import helpers.media_upload
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.media_upload.upload_user_images)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone_field', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
