# Generated by Django 5.0.1 on 2024-01-17 12:04

import helpers.media_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={},
        ),
        migrations.RemoveField(
            model_name='chef',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=1, upload_to=helpers.media_upload.upload_about_us),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='image',
            field=models.ImageField(default=2, upload_to=helpers.media_upload.upload_why_choose_us),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to=helpers.media_upload.upload_chef),
        ),
    ]
