# Generated by Django 5.0.1 on 2024-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_followus_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='follow_us_links',
        ),
        migrations.AddField(
            model_name='contactus',
            name='follow_us_links',
            field=models.ManyToManyField(blank=True, related_name='contact_us', to='home.followus'),
        ),
    ]
